### ISSUE TITLE
Senior Software Security Developers

### ISSUE THREAD

**Issue by vwangler** [tech256/jobs#278]
# Hiring Senior Software Security Developers!

### About Position
Star Lab is looking for senior software developers with a desire to explore and solve difficult security problems. Candidates are expected to be capable of contributing to the development, testing, and deployment of Linux Kernel and Xen Project/hypervisor tool suites that protect mission-critical and safety-critical systems from advanced threats. Experience with Intel and/or ARM virtualization and security/isolation technologies is highly desired. Applied cryptography, privilege separation, and systems security experience is highly desired. Linux and C software development proficiency is an absolute requirement, Python proficiency is highly desired, and Rust experience is highly desired. This position offers opportunities to contribute to OSS projects (Xen Project, Linux Kernel, Yocto/OpenEmbedded, etc.), expand Rust development experience, and work with a team of highly-experienced security engineers.

**Due to security requirements, US Citizenship is required.**

### Contact
- Tech256: (at)davidesler -- Reach out if you have any questions
- Location: Huntsville, AL -- New office at The Stovehouse
- E-mail: jobs@starlab.io

**Comment by tylerbhughes** [comment]
Thanks for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
