### ISSUE TITLE
GaN:  Radar Signal Analyst

### ISSUE THREAD

**Issue by omegix** [tech256/jobs#304]
# Hiring!

### About Position
This is a mid-level (journeyman) position that requires experience in MATLAB and some basic radar background. There are multiple openings for this position.  They do not have to be radar experts. They will be supporting design and development of algorithms in MATLAB.  A Secret clearance is required.

### Contact
- Tech256: HR@geeksandnerds.com
-- Include that you heard about position from Tech256 Job Board

**Comment by tylerbhughes** [comment]
Hi @omegix can you provide more information about this position for anyone viewing it?

**Comment by omegix** [comment]
Unfortunately no, that's as much as can be disclosed about this effort. I may be able to answer specific questions though.

**Comment by tylerbhughes** [comment]
Thanks for contributing to this issue. As it has been 90 days since the issue was originally opened, we are automatically closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
