### ISSUE TITLE
GaN:  IV&V Software Engineers 

### ISSUE THREAD

**Issue by omegix** [tech256/jobs#305]
# Hiring!

### About Position
The requirement is for Software Engineers/Software Developers with exposure to Formal Methods and IV&V. Any level of experience will be considered.  Requires a Secret clearance.

### Contact
- Tech256: HR@geeksandnerds.com
-- Include that you heard about position from Tech256 Job Board

**Comment by tylerbhughes** [comment]
Hi @omegix can you provide more information about this position for anyone viewing it?

**Comment by omegix** [comment]
Unfortunately no, that's as much as can be disclosed about this effort. I may be able to answer specific questions though.

**Comment by tylerbhughes** [comment]
Thanks for contributing to this issue. As it has been 90 days since the issue was originally opened, we are automatically closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
