### ISSUE TITLE
GaN:  Senior Software Developer \ Linux Kernel Dev

### ISSUE THREAD

**Issue by omegix** [tech256/jobs#306]
# Hiring!

### About Position
This position is looking for a real-time LINUX Kernel developer.  They will be working on the OS layer performance development for THAAD.  A Secret Clearance is required.

### Contact
- HR@geeksandnerds.com
-- Include that you heard about position from Tech256 Job Board

**Comment by tylerbhughes** [comment]
Hi @omegix can you provide more information about this position for anyone viewing it?

**Comment by omegix** [comment]
Unfortunately no, that's as much as can be disclosed about this effort.  I may be able to answer specific questions though.

**Comment by tylerbhughes** [comment]
Thanks for contributing to this issue. As it has been 90 days since the issue was originally opened, we are automatically closing the issue. This is often because the the job has already been filled and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
